### ISSUE TITLE
Protein sequence trimmed internally?

### ISSUE THREAD

**Issue by amorehead** [baker-laboratory/RoseTTAFold-All-Atom#124]
Hello.

When running RoseTTAFold-All-Atom using the following input YAML config file, I observed that the inference code returned a `.pdb` file that contains a predicted protein structure with the first 19 residues removed (as compared to the input FASTA sequence for this protein chain). Is there a reason why this particular sequence motif would be automatically removed by the code? For context, I noticed that the sequence alignment files (e.g., generated by HHblits) seem to show that the sequence was truncated before being passed downstream (e.g., to HHblits).

Config file input:
```yaml
# RoseTTAFold-All-Atom inference configuration file for input 'XYZ'
defaults:
  - base
job_name: "XYZ"

protein_inputs:
  a:
    fasta_file: /tmp/tmpvwt59__7/XYZ_A.fasta

sm_inputs:
  b:
    input: 'CCOC(=O)N(C)Cc1c(C(=O)O)n(Cc2cccc3ccccc23)c2ccc(F)cc12'
    input_type: "smiles"
```
where `/tmp/tmpvwt59__7/XYZ_A.fasta` has the following file contents:
```text
>A
MLLLPLPLLLFLLCSRAEAGEIIGGTESKPHSRPYMAYLEIVTSNGPSKFCGGFLIRRNFVLTAAHCAGRSITVTLGAHNITEEEDTWQKLEVIKQFRHPKYNTSTLHHDIMLLKLKEKASLTLAVGTLPFPSQKNFVPPGRMCRVAGWGRTGVLKPGSDTLQEVKLRLMDPQACSHFRDFDHNLQLCVGNPRKTKSAFKGDSGGPLLCAGVAQGIVSYGRSDAKPPAVFTRISHYRPWINQILQAN
```

Notably, in the output `.pdb` file (as attached), the first 19 residues (i.e., `MLLLPLPLLLFLLCSRAEA`) are not present in the resulting structure.

[L1001.pdb.txt](https://github.com/user-attachments/files/15594262/L1001.pdb.txt)
