### ISSUE TITLE
Double bond of ligand is being flipped from cis to trans during folding

### ISSUE THREAD

**Issue by therealsemechki** [baker-laboratory/RoseTTAFold-All-Atom#173]
I am trying to fold a simple test protein I designed with RFDaa and LigandMPNN that binds cis-azobenzene. Cis-azobenzene is fairly strained (two benzenes connected by a cis N=N), but should not isomerize on its own so easily/quickly.

If you would like to reproduce the issue, you can try it for yourself with this config file and protein fasta:

``` yaml
defaults:
  - base

job_name: "azobinder_with_ligand"
protein_inputs:
  A:
    fasta_file: inputs/azobinder.fasta

sm_inputs:
        B:
                input: N(=N/c1ccccc1)\c2ccccc2
                input_type: "smiles"
```

And this fasta file for the protein, azobinder.fasta:

```
>design_0_azobinder|Chain A
DAAARAALAALFADAAAAAAMDALAREAGLSLAEVRAARARLRRLAEAVAAGDEAALLALLSEDGRLLRDILLAADLVEAARARGDDALVAGWAPLARAAARALWLLLQREPENKLAREALKKLLDVWAADPFFAALREKFEAWMAAQAA
```

Is this an issue with the model, or is there a setting or script I may be able to change to prevent this? I'm not totally sure on where the error is occurring.

Thanks!
