### ISSUE TITLE
Error with many .sdf files - Failed to generate 3D coordinates for molecule

### ISSUE THREAD

**Issue by jmrussell** [baker-laboratory/RoseTTAFold-All-Atom#21]
I get this error after extracting the 'sdf' field from the ligands.json file included in the repo, I get it with quite a few of molecules. I can run peptide/nucleotide inferences without issue. Any ideas? The .sdf file looks fine to me.

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/apps/dev/containers/RoseTTAFold-All-Atom/local/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/opt/apps/dev/containers/RoseTTAFold-All-Atom/local/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/opt/apps/dev/containers/RoseTTAFold-All-Atom/local/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 81, in parse_inference_config
    sm_input = load_small_molecule(
  File "/opt/apps/dev/containers/RoseTTAFold-All-Atom/local/RoseTTAFold-All-Atom/rf2aa/data/small_molecule.py", line 16, in load_small_molecule
    obmol, msa, ins, xyz, mask = parse_mol(
  File "/opt/apps/dev/containers/RoseTTAFold-All-Atom/local/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 795, in parse_mol
    raise ValueError(f"Failed to generate 3D coordinates for molecule {filename}.")
ValueError: Failed to generate 3D coordinates for molecule HEM.sdf.
```

**Comment by r-krishna** [comment]
could you share a config/files to reproduce?

**Comment by jmrussell** [comment]
I'm using the base.yaml config for model params, and an example config would look like this:

```yaml
defaults:
  - base

job_name: NCR004

protein_inputs:
  A:
    fasta_file: input_fastas/NCR004.fasta

sm_inputs:
  B:
    input: HEB_ideal.sdf
    input_type: "sdf"
```

Here's the heb_ideal.sdf I tried: https://files.rcsb.org/ligands/download/HEB_model.sdf
and the smiles string: 

Cc1c2n3c(c1CCC(=O)O)C=C4C(=C(C5=[N]4[Fe]36[N]7=C(C=C8N6C(=C5)C(=C8C)C=C)C(=C(C7=C2)C)C=C)C)CCC(=O)O

**Comment by jmrussell** [comment]
FWIW, I have successfully ran this with both the zinc and calcium ideal .sdfs from the same source, so I suspect it's something with the heme.sdf.

**Comment by wqcui-lab** [comment]
Did you resolve the "Failed to generate 3D coordinates" problem? I encountered the same problem when dealing with this small molecule (heme.sdf).

**Comment by YaoYinYing** [comment]
Hi, I encounterred this error and googled around for this issue.  After enabling obff's logging to stdout, I see this: 
```text
SETTING UP BOND CALCULATIONS...
    COULD NOT FIND PARAMETERS FOR BOND 1-6 (IDX)...
```
`BOND 1-6` is an N-Fe bond, `mmff94` may not recognize it so after switching to `gaff`, the issue disappearred.

**Comment by Srichnew** [comment]
Hi YaoYinYang, how did you go about switching from mmff94 to gaff? 

Thank you in advance!

**Comment by YaoYinYing** [comment]
@Srichnew the last commit of my fork shows how. Good luck!

**Comment by Srichnew** [comment]
@YaoYinYing, I found it and will be trying it out shortly. Thanks so much!

**Comment by Srichnew** [comment]
@YaoYinYing Sorry, having issues installing pytorch given your branch instructions. it's saying pytorch=2.0.1 is not available from the current channels. Do you have a solution?

**Comment by YaoYinYing** [comment]
> @YaoYinYing Sorry, having issues installing pytorch given your branch instructions. it's saying pytorch=2.0.1 is not available from the current channels. Do you have a solution?

@Srichnew It is weird that conda reports pytorch=2.0.1 not available. I performed `conda search` on both Ubuntu X64 and Macbook Pro with M1 chip using the exact ` conda search pytorch -c conda-forge -c bioconda -c biocore`, and they both return with this version listed.

**Comment by Srichnew** [comment]
Yes, that's what I thought as well after finding on anaconda's page. Here's a screenshot though; I've never run into this before, sorry.
![pytorch](https://github.com/user-attachments/assets/3a5beead-d251-4e4e-bea3-851b33db90ff)

**Comment by Srichnew** [comment]
@YaoYinYing I think it potetntially had to do with using miniforge3 instead of mambaforge. After removing miniforge3 and installing mambaforge, everything installed correctly including pytorch==2.0.1

Thank you for updating your readme!

**Comment by Srichnew** [comment]
@YaoYinYing
For the signalp6 installation step, is there a step I'm missing during this stage? The only options for downloading signalp6 that i've found trace back to registering on their website and downloading the .tar.gz before unpacking and trying to install it manually, which doesn't seem to work all that well for me. 

Thank you for all of the help.

**Comment by YaoYinYing** [comment]
> @YaoYinYing I think it potetntially had to do with using miniforge3 instead of mambaforge. After removing miniforge3 and installing mambaforge, everything installed correctly including pytorch==2.0.1
> 
> Thank you for updating your readme!

Great, glad to hear this!



> @YaoYinYing For the signalp6 installation step, is there a step I'm missing during this stage? The only options for downloading signalp6 that i've found trace back to registering on their website and downloading the .tar.gz before unpacking and trying to install it manually, which doesn't seem to work all that well for me.
> 
> Thank you for all of the help.

Well - you have to fetch a binary build of signalp6 to help you with pretrained weight extraction from downloaded tar file.  This binary is open-access via conda:
```shell
conda install -y -c conda-forge -c bioconda -c predector  -c biocore hhsuite signalp6 psipred
```
What you register for is acturally the weights inside `signalp-6.0h.fast.tar.gz`. You dont have to unpack it manually.
```shell
signalp6-register signalp-6.0h.fast.tar.gz
```
This step helps you with a lot of workarounds like dependency fetching, unpacking, testing and etc.
If you encounter issue like `iOSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory`, you need to run `pip install mkl` and do this again.

Then rename it.
```shell
mv $CONDA_PREFIX/lib/python3.10/site-packages/signalp/model_weights/distilled_model_signalp6.pt $CONDA_PREFIX/lib/python3.10/site-packages/signalp/model_weights/ensemble_model_signalp6.pt
```

**Comment by Srichnew** [comment]
@YaoYinYing Thank you, that makes sense. However, when I run the signalp6-register command with the .tar.gz zip, I see this error (additionally, no weights are found in $CONDA_PREFIX/lib/python3.10/site-packages/signalp/model_weights/ following this error):

```
Stored in directory: /home/shane/.cache/pip/wheels/8b/ab/ef/d6ee779a78ba70fe1a727b36ab5d062ed4bfda9f822ed2622c
Successfully built signalp6
Installing collected packages: signalp6

  changing mode of /home/shane/mambaforge/envs/rf2aa/bin/signalp6 to 775
Successfully installed signalp6-6.0+h
Remote version of pip: 24.2
Local version of pip:  24.2
Was pip installed by pip? False
Removed build tracker: '/tmp/pip-build-tracker-axubft78'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/signalp/__init__.py", line 4, in <module>
    from .predict import main
  File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/signalp/predict.py", line 29, in <module>
    import torch
  File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

**Comment by YaoYinYing** [comment]
> @YaoYinYing Thank you, that makes sense. However, when I run the signalp6-register command with the .tar.gz zip, I see this error (additionally, no weights are found in $CONDA_PREFIX/lib/python3.10/site-packages/signalp/model_weights/ following this error):
> 
> ```
> Stored in directory: /home/shane/.cache/pip/wheels/8b/ab/ef/d6ee779a78ba70fe1a727b36ab5d062ed4bfda9f822ed2622c
> Successfully built signalp6
> Installing collected packages: signalp6
> 
>   changing mode of /home/shane/mambaforge/envs/rf2aa/bin/signalp6 to 775
> Successfully installed signalp6-6.0+h
> Remote version of pip: 24.2
> Local version of pip:  24.2
> Was pip installed by pip? False
> Removed build tracker: '/tmp/pip-build-tracker-axubft78'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/signalp/__init__.py", line 4, in <module>
>     from .predict import main
>   File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/signalp/predict.py", line 29, in <module>
>     import torch
>   File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
>     from torch._C import *  # noqa: F403
> ImportError: /home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
> ```

@Srichnew Can you try reinstall this conda env with 
```shell
mamba install -y -c conda-forge -c pytorch -c bioconda -c nvidia -c biocore mkl=2024.0.0 absl-py pytorch=2.0.1 pytorch-cuda=11.8 torchaudio=2.0.2 torchtriton=2.0.0 torchvision=0.15.2 dgl=1.1.2 openbabel pandas requests scikit-learn=1.4.1.post1 scipy  tensorflow=2.11.0 omegaconf gitpython hydra-core numpy h5py hdf5 icecream click deepdiff

# Tools of sequence preprocessing
mamba install -y -c conda-forge -c bioconda -c predector  -c biocore hhsuite signalp6 psipred 

pip install git+https://github.com/YaoYinYing/SE3Transformer@rf2aa 
pip install assertpy pydantic

pip install git+https://github.com/YaoYinYing/RoseTTAFold-All-Atom --no-dependencies   --no-cache-dir
```

See this https://github.com/pytorch/pytorch/issues/123097#issuecomment-2055236551

**Comment by Srichnew** [comment]
Alright, so that installation seems to actually be functioning, but I think now there's just something interesting happening with the database settings in the base.yaml file within the environment's rf2aa/config/ directory. 

```
python -m rf2aa.run_inference --config-name omcs-hec-2.yaml
Using the cif atom ordering for TRP.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 206, in main
    runner = ModelRunner(config)
  File "/home/shane/mambaforge/envs/rf2aa/lib/python3.10/site-packages/rf2aa/run_inference.py", line 28, in __init__
    self.ffdb = FFindexDB(read_index(config.database_params.DB_PDB100+'_pdb.ffindex'),
omegaconf.errors.ConfigAttributeError: Key 'DB_PDB100' is not in struct
    full_key: database_params.DB_PDB100
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I did notice that your base.yaml used a different UniRef30 database version (2022_01, I think), but this seems like it has more to do with the pdb100 database.

Here's my base.yaml:
```
job_name: "structure_prediction"
output_path: "output/structure_prediction"
checkpoint_path: /data-2/db/weights/RFAA_paper_weights.pt
database_params:
  DB_UR30: "/data-2/db/UniRef30_2020_06/UniRef30_2020_06"
  DB_BFD: "/data-2/db/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.>
  DB_PDB100: "/data-2/db/pdb100/pdb100_2021Mar03"
  command: make_msa.sh
  num_cpus: 32
  mem: 256

force_cpu: False # force to use cpu if CUDA out of memory
protein_inputs: null
na_inputs: null
sm_inputs: null
covale_inputs:  null
residue_replacement: null

chem_params:
  use_phospate_frames_for_NA: True
  use_cif_ordering_for_trp: True

loader_params:
  n_templ: 4
  MAXLAT: 128
  MAXSEQ: 1024
  MAXCYCLE: 4
  BLACK_HOLE_INIT: False
  seqid: 150.0


legacy_model_param:
  n_extra_block: 4
  n_main_block: 32
  n_ref_block: 4
  n_finetune_block: 0
  d_msa: 256
  d_msa_full: 64
  d_pair: 192
  d_templ: 64
  n_head_msa: 8
  n_head_pair: 6
  n_head_templ: 4
  d_hidden_templ: 64
  p_drop: 0.0
  use_chiral_l1: True
  use_lj_l1: True
  use_atom_frames: True
  recycling_type: "all"
  use_same_chain: True
  lj_lin: 0.75
  SE3_param:
    num_layers: 1
```
