### ISSUE TITLE
bad prediction for a homodimer

### ISSUE THREAD

**Issue by lucl13** [baker-laboratory/RoseTTAFold-All-Atom#55]
Hi all, 

I'm using the config file below to do a homodimer prediction. But the prediction seems to be bad as there are clashes between two protomers. 

```

defaults:
  - base

job_name: pfka_dimer

protein_inputs:
  A: 
    fasta_file: $WORK_DIR/pfka.fasta
  B:
    fasta_file: $WORK_DIR/pfka.fasta

```

did I miss something?

![img_v3_0295_ce207c83-a664-47ed-b513-d06ba7de20cg](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/assets/25299332/79355271-4c93-4666-805b-395a8eb49b3d)
